In [1]:
import pandas as pd

In [2]:
# import NY Taxi zones information

df_zones = pd.read_csv("taxi_zone_lookup.csv")

In [3]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [4]:
df_zones

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

In [5]:
!pwd

/Users/ginadurante/Documents/GitHub/data-engineering-zoomcamp/pipeline

In [6]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /opt/miniconda3/envs/dtc/lib/python3.13/site-packages (2.9.11)

In [7]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [8]:
df_zones.to_sql(name="zones", con=engine, if_exists="replace")

265